---
# tasks file for k8s-worker
- name: Checking, if some files are existed
  shell: if [ -f /etc/kubernetes/kubelet.conf ]; then echo 0; else echo 1; fi
  register: kubectl_exist

- name: Reset Kubernetes components
  when: kubectl_exist.stdout != "0"
  shell: kubeadm reset --force
  notify:
    - Join Worker to Cluster
